"""correccion

Revision ID: 4ef4420b9e71
Revises: 2f5f10777d4b
Create Date: 2024-06-15 16:06:20.674691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ef4420b9e71'
down_revision = '2f5f10777d4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('moroso')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('moroso', sa.VARCHAR(length=20), nullable=False))

    # ### end Alembic commands ###
