"""Campo precio agregado

Revision ID: 66aae9ca7bb4
Revises: 9050e00e5b42
Create Date: 2024-07-02 19:42:35.237034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66aae9ca7bb4'
down_revision = '9050e00e5b42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('curso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('curso', schema=None) as batch_op:
        batch_op.drop_column('precio')

    # ### end Alembic commands ###
