"""Reparar nombre de constraint en clave externa de Curso

Revision ID: 9050e00e5b42
Revises: 
Create Date: 2024-07-02 19:36:16.033942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9050e00e5b42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('curso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_profesor', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_curso_usuario', 'usuario', ['id_profesor'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('curso', schema=None) as batch_op:
        batch_op.drop_constraint('fk_curso_usuario', type_='foreignkey')
        batch_op.drop_column('id_profesor')

    # ### end Alembic commands ###
